version: "3.7"

services:
  rpg-bot:
    container_name: rpg-bot
    build:
      context: .
      target: development
    volumes:
      - .:/app

  rpg-bot-test:
    container_name: rpg-bot-test
    build:
      context: .
      target: test
